# Redirects plain HTTP to HTTPS for shopmon.fos.gg.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shopmon-prod-redirect
  namespace: shopmon-prod
spec:
  parentRefs:
    - name: eg
      namespace: default
      sectionName: fos-gg-http
  hostnames:
    - shopmon.fos.gg
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
