apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopmon-staging
resources:
  - namespace.yaml
  - ../base
  - secret.yaml
  - configmap.yaml
  - db.yaml
  - db-backup.yaml
  - httproute.yaml
  - httproute-redirect.yaml
images:
  - name: ghcr.io/friendsofshopware/shopmon
    newTag: main-1784467736-9111a4b # {"$imagepolicy": "flux-system:shopmon-staging:tag"}
