apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 10m
  releaseName: eg
  targetNamespace: envoy-gateway-system
  storageNamespace: envoy-gateway-system
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
