apiVersion: v1
kind: ConfigMap
metadata:
  name: shopmon-config
  namespace: shopmon-staging
data:
  REDIS_URL: "redis://redis:6379"
  FRONTEND_URL: "https://shopmon.staging.fos.gg"
  MAIL_FROM: "Shopmon <noreply@fos.gg>"
  SMTP_REPLY_TO: "noreply@fos.gg"
  APP_SITESPEED_ENDPOINT: "https://sitespeed.fos.gg"
  APP_SITESPEED_PREFIX: "shopmon-staging-"
  PACKAGES_API_URL: "https://packages.staging.fos.gg"
  OTEL_DEPLOYMENT_ENVIRONMENT: "staging"
