apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
  namespace: sitespeed
spec:
  provider:
    onepasswordSDK:
      vault: Shopmon
      auth:
        serviceAccountSecretRef:
          name: op-token
          key: token
      cache:
        ttl: 5m
        maxSize: 100
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sitespeed
  namespace: sitespeed
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: S3_BUCKET_NAME
      remoteRef:
        key: Sitespeed Production/S3_BUCKET_NAME
    - secretKey: S3_SERVICE_URL
      remoteRef:
        key: Sitespeed Production/S3_SERVICE_URL
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: Sitespeed Production/S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: Sitespeed Production/S3_SECRET_KEY
    - secretKey: AUTH_TOKEN
      remoteRef:
        key: Sitespeed Production/AUTH_TOKEN
