apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
  namespace: swdemo
spec:
  provider:
    onepasswordSDK:
      vault: Shopmon
      auth:
        serviceAccountSecretRef:
          name: op-token
          key: token
      cache:
        ttl: 5m
        maxSize: 100
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: swdemo
  namespace: swdemo
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    name: swdemo
    creationPolicy: Owner
  data:
    - secretKey: SHOPWARE_ADMIN_PASSWORD
      remoteRef:
        key: Demo Instance/password
    - secretKey: SHOPMON_ACCESS_KEY
      remoteRef:
        key: Demo Instance/CLIENT_ID
    - secretKey: SHOPMON_ACCESS_SECRET
      remoteRef:
        key: Demo Instance/CLIENT_SECRET
